#pragma once

#include "Logging/LogMacros.h"

CODEREDREBOOT_API DECLARE_LOG_CATEGORY_EXTERN(LogBaseAbilitySystem, Log, All);
CODEREDREBOOT_API DECLARE_LOG_CATEGORY_EXTERN(LogBaseCharacter, Log, All);
CODEREDREBOOT_API DECLARE_LOG_CATEGORY_EXTERN(LogBaseInput, Log, All);
CODEREDREBOOT_API DECLARE_LOG_CATEGORY_EXTERN(LogMultiGameInstance, Log, All);
CODEREDREBOOT_API DECLARE_LOG_CATEGORY_EXTERN(LogHubGameMode, Log, All);
CODEREDREBOOT_API DECLARE_LOG_CATEGORY_EXTERN(LogLevelLoading, Log, All);
CODEREDREBOOT_API DECLARE_LOG_CATEGORY_EXTERN(LogBasePlayerController, Log, All);
CODEREDREBOOT_API DECLARE_LOG_CATEGORY_EXTERN(LogBaseUI, Log, All);